baseURL = "http://wesovilabs.com/koazee/"
languageCode = "en-us"
publishDir = "../docs"
title = "Koazee"
theme = "kube"
description = "Lazy like a koala, smart like a chimpanzee"
pygmentsCodeFences=true
pygmentsUseClasses=true
pygmentsStyle = "monokai"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Iván Corrales Solera"
  github = "https://github.com/ivancorrales"
  twitter = "@wesovilabs"
  email = "ivan.corrales.solera@gmail.com"

[[menu.main]]
    name = "Getting started"
    weight = -100
    url = "/getting-started/"

[[menu.main]]
    name = "Documentation"
    weight = -99
    url = "/docs/"
[[menu.main]]
    name = "Guides & Tutorials"
    weight = -98
    url = "/guides/"
